name: Manual MIPSLE Build

# 仅保留手动触发
on: 
  workflow_dispatch: 

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux_build_mipsle:
    # 移除 matrix，直接定义目标环境
    runs-on: ubuntu-latest 
    name: Linux MIPSLE Build
    
    # 定义静态变量
    env:
      BUILD_ARCH: mipsle
      ARTIFACT_NAME: subconverter_mipsle
      
    steps:
    - name: Checkout base
      uses: actions/checkout@v4
      
    # 这一步可以保留，但不再依赖 matrix
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
      
    # 使用 env 变量进行构建
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:${{ env.BUILD_ARCH }}-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: subconverter/
        
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      run: tar czf ${{ env.ARTIFACT_NAME }}.tar.gz subconverter
      
    - name: Draft Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ARTIFACT_NAME }}.tar.gz
        draft: true
